// <auto-generated />
using System;
using Core.Lib.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Lib.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260111042336_AddTableCryptoCatalog")]
    partial class AddTableCryptoCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Crypto")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Lib.Domain.Entities.CryptoAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("CryptoCatalog", "Crypto");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8d64c02-4638-4e6f-80d5-53305047f3b1"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Bitcoin",
                            IsActive = true,
                            Key = "btc",
                            Symbol = "BTCUSDT"
                        },
                        new
                        {
                            Id = new Guid("a5e2f7b8-9c1d-4e2a-8f3b-6c4d9e0a1f2b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Ethereum",
                            IsActive = true,
                            Key = "eth",
                            Symbol = "ETHUSDT"
                        },
                        new
                        {
                            Id = new Guid("c1b3d4e5-6f7a-8b9c-0d1e-2f3a4b5c6d7e"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Dogecoin",
                            IsActive = true,
                            Key = "doge",
                            Symbol = "DOGEUSDT"
                        },
                        new
                        {
                            Id = new Guid("f9e8d7c6-b5a4-3f2e-1d0c-9b8a7f6e5d4c"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Solana",
                            IsActive = true,
                            Key = "sol",
                            Symbol = "SOLUSDT"
                        },
                        new
                        {
                            Id = new Guid("e1d2c3b4-a5f6-7e8d-9c0b-1a2f3e4d5c6b"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "XRP",
                            IsActive = true,
                            Key = "xrp",
                            Symbol = "XRPUSDT"
                        });
                });

            modelBuilder.Entity("Core.Lib.Domain.Entities.MarketHistory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("Coin");

                    b.HasIndex("Timestamp");

                    b.ToTable("MarketHistory", "Crypto");
                });
#pragma warning restore 612, 618
        }
    }
}
